name: Build AlNawazat APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Warning ignore karein, 20 zyada stable hai builds ke liye

      - name: Install Dependencies
        run: npm install --force

      - name: Create WWW Folder
        run: mkdir -p www && echo "<html><body>AlNawazat</body></html>" > www/index.html

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AlNawazat-Test-App
          path: android/app/build/outputs/apk/debug/app-debug.apk